///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/song05.aks
/// Generation time: domingo, 16 de octubre de 2016, 22:31:09 CEST
///

/// Song 'song05' metadata macros
#define song05_address  0x252
#define song05_size          196
#define song05_end      0x316

/// Song 'song05' array declaration
extern void song05[song05_size];
