///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/song00.aks
/// Generation time: sábado, 22 de octubre de 2016, 10:33:57 CEST
///

/// Song 'song00' metadata macros
#define song00_address  0x400
#define song00_size           45
#define song00_end      0x42D

/// Song 'song00' array declaration
extern void song00[song00_size];
