///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/song05.aks
/// Generation time: viernes,  7 de octubre de 2016, 01:11:37 CEST
///

/// Song 'song05' metadata macros
#define song05_address  0x1000
#define song05_size          196
#define song05_end      0x10C4

/// Song 'song05' array declaration
extern void song05[song05_size];
