///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: images/song02.aks
/// Generation time: viernes, 30 de septiembre de 2016, 00:49:58 CEST
///

/// Song 'song' metadata macros
#define song_address  0x200
#define song_size          529

/// Song 'song' array declaration
extern void song[song_size];
