///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/song05.aks
/// Generation time: lunes,  3 de octubre de 2016, 00:50:41 CEST
///

/// Song 'song05' metadata macros
#define song05_address  0x1000
#define song05_size          195

/// Song 'song05' array declaration
extern void song05[song05_size];
