///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/song02.aks
/// Generation time: viernes,  7 de octubre de 2016, 01:11:38 CEST
///

/// Song 'song02' metadata macros
#define song02_address  0x200
#define song02_size          529
#define song02_end      0x411

/// Song 'song02' array declaration
extern void song02[song02_size];
