///
///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: Song02.aks
/// Generation time: miércoles, 28 de septiembre de 2016, 00:15:14 CEST
///

/// Song 'g_music' metadata macros
#define g_music_address  200
#define g_music_size          532

/// Song 'g_music' array declaration
extern void g_music[g_music_size];
